In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
electricity_exchange_market_price_2023=pd.read_csv("../../DataSources/electricity_exchange_market_price_2023.csv", sep=";", nrows=5)
electricity_exchange_market_price_2023

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2023 00:00,"0,5808","0,484"
1,01.01.2023 01:00,"0,2412","0,201"
2,01.01.2023 02:00,"0,1656","0,138"
3,01.01.2023 03:00,"0,0108","0,009"
4,01.01.2023 04:00,"0,0096","0,008"

In [13]:
electricity_exchange_market_price_2024=pd.read_csv("../../DataSources/electricity_exchange_market_price_2024.csv", sep=";", nrows=5)
electricity_exchange_market_price_2024

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2024 00:00,"4,88122","4,001"
1,01.01.2024 01:00,"4,68114","3,837"
2,01.01.2024 02:00,"3,47212","2,846"
3,01.01.2024 03:00,"3,25252","2,666"
4,01.01.2024 04:00,"2,98656","2,448"

In [14]:
electricity_exchange_market_price_2025=pd.read_csv("../../DataSources/electricity_exchange_market_price_2025.csv", sep=";", nrows=5)
electricity_exchange_market_price_2025

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2025 00:00,"0,48922","0,401"
1,01.01.2025 01:00,"0,5917","0,485"
2,01.01.2025 02:00,"0,4819","0,395"
3,01.01.2025 03:00,"0,4636","0,38"
4,01.01.2025 04:00,"0,42212","0,346"

In [36]:
df1 = pd.read_csv("../../DataSources/electricity_exchange_market_price_2023.csv", sep=";")
df2 = pd.read_csv("../../DataSources/electricity_exchange_market_price_2024.csv", sep=";")
df3 = pd.read_csv("../../DataSources/electricity_exchange_market_price_2025.csv", sep=";")
df_all = pd.concat([df1, df2, df3], ignore_index=True)
df_all.to_csv("../../DataSources/electricity_exchange_market_price_combined_raw.csv", index=False)
df_all.head()

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2023 00:00,"0,5808","0,484"
1,01.01.2023 01:00,"0,2412","0,201"
2,01.01.2023 02:00,"0,1656","0,138"
3,01.01.2023 03:00,"0,0108","0,009"
4,01.01.2023 04:00,"0,0096","0,008"

In [19]:
fictional_households_electricity_consumption=pd.read_csv("../../DataSources/fictional_households_electricity_consumption.csv")
fictional_households_electricity_consumption

       household_id            timestamp  consumption_kwh
0        EE_APT_001  2023-01-01 00:00:00           0.0502
1        EE_APT_002  2023-01-01 00:00:00           0.0861
2        EE_APT_003  2023-01-01 00:00:00           0.1124
3        EE_APT_004  2023-01-01 00:00:00           0.1694
4        EE_APT_005  2023-01-01 00:00:00           1.2910
...             ...                  ...              ...
789115   EE_ROW_001  2025-12-31 23:00:00           0.3949
789116   EE_ROW_002  2025-12-31 23:00:00           0.6089
789117   EE_ROW_003  2025-12-31 23:00:00           1.9991
789118   EE_ROW_004  2025-12-31 23:00:00           0.3130
789119   EE_ROW_005  2025-12-31 23:00:00           0.2343

[789120 rows x 3 columns]

In [23]:
fictional_vendor_exchange_market_pricing=pd.read_csv("../../DataSources/fictional_vendor_exchange_market_pricing.csv", header=1, index_col=0, nrows=5)
fictional_vendor_exchange_market_pricing

,plan_id,electricity_vendor_name,electricity_plan_name,monthly_price,margin_price
NaN,1,Example Vendor,Example Plan,0,0

In [24]:
fictional_vendor_fixed_pricing=pd.read_csv("../../DataSources/fictional_vendor_fixed_pricing.csv", header=1, index_col=0, nrows=5)
fictional_vendor_fixed_pricing

,plan_id,electricity_vendor_name,electricity_plan_name,monthly_price,kwh_price
NaN,1,Example Vendor 1,Example Plan 1,0,0.10
NaN,2,Example Vendor 2,Example Plan A,1,0.09