## Test

In [2]:
# VAJALIKUD LISAD KOODI KIRJUTAMISEKS
import streamlit as st
import pandas as pd
import duckdb


# VAJALIKUD LISAD GRAAFIKUTE TEGEMISEKS
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
""" 
Kuidas teha UNION JOIN kolmest tabelist, mille veerunimed on eraldatud semikooloniga ja veeruväärtused komaga
"""


#electricity_exchange_market_price_2023=pd.read_csv("../../DataSources/electricity_exchange_market_price_2023.csv", sep=";", decimal=',')
#electricity_exchange_market_price_2024=pd.read_csv("../../DataSources/electricity_exchange_market_price_2024.csv", sep=";", decimal=',')
#electricity_exchange_market_price_2025=pd.read_csv("../../DataSources/electricity_exchange_market_price_2025.csv", sep=";", decimal=',')
#electricity_exchange_market_price_combined = pd.concat([electricity_exchange_market_price_2023, electricity_exchange_market_price_2024, electricity_exchange_market_price_2025], ignore_index=True)
#electricity_exchange_market_price_combined.to_csv("../../DataSources/electricity_exchange_market_price_combined.csv", index=False)

#electricity_exchange_market_price_combined

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2023 00:00,0.58080,0.4840
1,01.01.2023 01:00,0.24120,0.2010
2,01.01.2023 02:00,0.16560,0.1380
3,01.01.2023 03:00,0.01080,0.0090
4,01.01.2023 04:00,0.00960,0.0080
...,...,...,...
26230,30.12.2025 20:00,11.88850,9.5875
26231,30.12.2025 21:00,11.52115,9.2912
26232,30.12.2025 22:00,10.29572,8.3030
26233,30.12.2025 23:00,10.42809,8.4097
26234,31.12.2025 00:00,9.57559,7.7222

In [ ]:
""" 
Kuidas leida rea index number, kui sa tead, mis rea väärtus on
"""
# electricity_exchange_market_price_combined[electricity_exchange_market_price_combined['Periood'] == '29.10.2023 03:00'].index

RangeIndex(start=7226, stop=7228, step=1)

In [ ]:
# electricity_exchange_market_price_combined[electricity_exchange_market_price_combined['Periood'] == '27.10.2024 03:00'].index

RangeIndex(start=15939, stop=15941, step=1)

In [ ]:
# electricity_exchange_market_price_combined[electricity_exchange_market_price_combined['Periood'] == '26.10.2025 03:00'].index

RangeIndex(start=24652, stop=24654, step=1)

In [ ]:
""" 
Kuidas kustutada kindlad read, kui sa tead rea index number
"""
# electricity_exchange_market_price_combined = electricity_exchange_market_price_combined.drop([7226, 15939, 24652])

In [ ]:
""" 
Kuidas vaadata, et kustutatud ridade võrra tabeli ridadearv väheneks
"""
# electricity_exchange_market_price_combined = electricity_exchange_market_price_combined.drop([7226, 15939, 24652])electricity_exchange_market_price_combined

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2023 00:00,0.58080,0.4840
1,01.01.2023 01:00,0.24120,0.2010
2,01.01.2023 02:00,0.16560,0.1380
3,01.01.2023 03:00,0.01080,0.0090
4,01.01.2023 04:00,0.00960,0.0080
...,...,...,...
26230,30.12.2025 20:00,11.88850,9.5875
26231,30.12.2025 21:00,11.52115,9.2912
26232,30.12.2025 22:00,10.29572,8.3030
26233,30.12.2025 23:00,10.42809,8.4097
26234,31.12.2025 00:00,9.57559,7.7222

In [ ]:
fictional_households_electricity_consumption=pd.read_csv("../../DataSources/fictional_households_electricity_consumption.csv", nrows=5)
fictional_households_electricity_consumption

  household_id            timestamp  consumption_kwh
0   EE_APT_001  2023-01-01 00:00:00           0.0502
1   EE_APT_002  2023-01-01 00:00:00           0.0861
2   EE_APT_003  2023-01-01 00:00:00           0.1124
3   EE_APT_004  2023-01-01 00:00:00           0.1694
4   EE_APT_005  2023-01-01 00:00:00           1.2910

In [20]:
electricity_exchange_market_price_2023['Periood'] = pd.to_datetime(electricity_exchange_market_price_2023['Periood'], format='%d.%m.%Y %H:%M')
fictional_households_electricity_consumption['timestamp'] = pd.to_datetime(fictional_households_electricity_consumption['timestamp'])

In [22]:
fictional_vendor_exchange_market_pricing=pd.read_csv("../../DataSources/fictional_vendor_exchange_market_pricing.csv", header=1, index_col=0, nrows=5).reset_index(drop=True)
fictional_vendor_exchange_market_pricing

,plan_id,electricity_vendor_name,electricity_plan_name,monthly_price,margin_price
0,1,Example Vendor,Example Plan,0,0

In [21]:
fictional_vendor_fixed_pricing=pd.read_csv("../../DataSources/fictional_vendor_fixed_pricing.csv", header=1, index_col=0, nrows=5).reset_index(drop=True)
fictional_vendor_fixed_pricing

,plan_id,electricity_vendor_name,electricity_plan_name,monthly_price,kwh_price
0,1,Example Vendor 1,Example Plan 1,0,0.10
1,2,Example Vendor 2,Example Plan A,1,0.09

In [19]:
fictional_households_electricity_consumption

       household_id            timestamp  consumption_kwh
0        EE_APT_001  2023-01-01 00:00:00           0.0502
1        EE_APT_002  2023-01-01 00:00:00           0.0861
2        EE_APT_003  2023-01-01 00:00:00           0.1124
3        EE_APT_004  2023-01-01 00:00:00           0.1694
4        EE_APT_005  2023-01-01 00:00:00           1.2910
...             ...                  ...              ...
789115   EE_ROW_001  2025-12-31 23:00:00           0.3949
789116   EE_ROW_002  2025-12-31 23:00:00           0.6089
789117   EE_ROW_003  2025-12-31 23:00:00           1.9991
789118   EE_ROW_004  2025-12-31 23:00:00           0.3130
789119   EE_ROW_005  2025-12-31 23:00:00           0.2343

[789120 rows x 3 columns]