In [ ]:
import pandas as pd

df_consumption = pd.read_csv("../../DataSources/fictional_households_electricity_consumption.csv")
df_price_2025 = pd.read_csv("../../DataSources/electricity_exchange_market_price_2025.csv", sep=";", decimal=',')
df_fixed = pd.read_csv("../../DataSources/fictional_vendor_fixed_pricing.csv")
df_exchange = pd.read_csv("../../DataSources/fictional_vendor_exchange_market_pricing.csv")

In [49]:
df_consumption

       household_id            timestamp  consumption_kwh
0        EE_APT_001  2023-01-01 00:00:00           0.0502
1        EE_APT_002  2023-01-01 00:00:00           0.0861
2        EE_APT_003  2023-01-01 00:00:00           0.1124
3        EE_APT_004  2023-01-01 00:00:00           0.1694
4        EE_APT_005  2023-01-01 00:00:00           1.2910
...             ...                  ...              ...
789115   EE_ROW_001  2025-12-31 23:00:00           0.3949
789116   EE_ROW_002  2025-12-31 23:00:00           0.6089
789117   EE_ROW_003  2025-12-31 23:00:00           1.9991
789118   EE_ROW_004  2025-12-31 23:00:00           0.3130
789119   EE_ROW_005  2025-12-31 23:00:00           0.2343

[789120 rows x 3 columns]

In [50]:
df_price_2025

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2025 00:00,0.48922,0.4010
1,01.01.2025 01:00,0.59170,0.4850
2,01.01.2025 02:00,0.48190,0.3950
3,01.01.2025 03:00,0.46360,0.3800
4,01.01.2025 04:00,0.42212,0.3460
...,...,...,...
8732,30.12.2025 20:00,11.88850,9.5875
8733,30.12.2025 21:00,11.52115,9.2912
8734,30.12.2025 22:00,10.29572,8.3030
8735,30.12.2025 23:00,10.42809,8.4097
8736,31.12.2025 00:00,9.57559,7.7222

In [51]:
df_new_price_2025 = df_price_2025.rename(columns={"Periood": "timestamp", "Börsihind senti/kWh (sisaldab käibemaksu)": "market_price_with_km", "Börsihind senti/kWh (ei sisalda käibemaksu)": "market_price_without_km"})
df_new_price_2025

             timestamp  market_price_with_km  market_price_without_km
0     01.01.2025 00:00               0.48922                   0.4010
1     01.01.2025 01:00               0.59170                   0.4850
2     01.01.2025 02:00               0.48190                   0.3950
3     01.01.2025 03:00               0.46360                   0.3800
4     01.01.2025 04:00               0.42212                   0.3460
...                ...                   ...                      ...
8732  30.12.2025 20:00              11.88850                   9.5875
8733  30.12.2025 21:00              11.52115                   9.2912
8734  30.12.2025 22:00              10.29572                   8.3030
8735  30.12.2025 23:00              10.42809                   8.4097
8736  31.12.2025 00:00               9.57559                   7.7222

[8737 rows x 3 columns]

In [52]:
df_new_price_2025 = df_new_price_2025.astype({"market_price_with_km": float, "market_price_without_km": float})

In [ ]:
df_new_price_2025

             timestamp  market_price_with_km  market_price_without_km
0     01.01.2025 00:00               0.48922                   0.4010
1     01.01.2025 01:00               0.59170                   0.4850
2     01.01.2025 02:00               0.48190                   0.3950
3     01.01.2025 03:00               0.46360                   0.3800
4     01.01.2025 04:00               0.42212                   0.3460
...                ...                   ...                      ...
8732  30.12.2025 20:00              11.88850                   9.5875
8733  30.12.2025 21:00              11.52115                   9.2912
8734  30.12.2025 22:00              10.29572                   8.3030
8735  30.12.2025 23:00              10.42809                   8.4097
8736  31.12.2025 00:00               9.57559                   7.7222

[8737 rows x 3 columns]